apiVersion: v1
kind: PersistentVolume
metadata:
  name: robot-shop-redis-pv
  namespace: robot-shop
  labels:
    type: local
    service: redis
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
